server:
  port: 8080

management:
  server.port: 8081
  endpoints:
    enabed-by-default: true
    web.base-path: /

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: learning-mongo
      username: root
      password: example